### PR TITLE
fix: allow to render docs without react-router

### LINKED ISSUE #1201: HttpService doesn't work in isolation (and tests don't show it)
Screenshot from 2021-05-10 14-59-22

We seem to have 2 separate problems.

In our storybook it complains that `Uncaught TypeError: useContext(...) is undefined`

On the other hand in studio PR (https://github.com/stoplightio/platform-internal/pull/6126) there seems to be a router issue (they are not wrapping ParsedDocs in a Router and they shouldn't).

This is highlighted again in our test suite, where we have to wrap `HttpOperation` in `Router` in order for tests to pass.

Screenshot from 2021-05-10 15-02-51

This is however a wrong strategy, because this makes `Docs` and `ParsedDocs` unrenderable outside of Router. Additionally when this component is used in some other app then `elements`, it might pick-up errorenous routes from "mother application".

### PR DESCRIPTION
**Pull request by mpodlasin**
Closes #1201

### CODE REVIEW

File: packages/elements-core/src/components/Docs/HttpService/HttpService.tsx [hunk 1]
```diff
@@ -64,7 +63,7 @@ const HttpServiceComponent = React.memo<HttpServiceProps>(({ className, data, he
       ) : (
         <Box mb={10}>
           {description}
-          <PoweredByLink source={data.name ?? 'no-title'} pathname={pathname} packageType="elements" headless />
+          {pathname && <PoweredByLink source={data.name ?? 'no-title'} pathname={pathname} packageType="elements" headless />}
```
Comment (philsturgeon) [inline packages/elements-core/src/components/Docs/HttpService/HttpService.tsx:66]: Does this mean the powered by link is sometimes hidden?

Comment (mpodlasin) [reply packages/elements-core/src/components/Docs/HttpService/HttpService.tsx:66]: Yes, in `platform-internal` usages.

Comment (mpodlasin) [reply packages/elements-core/src/components/Docs/HttpService/HttpService.tsx:66]: ...and when we forget to provide proper props, so I will actually add e2e test that it is actually visible in API.

I don't remember if it was supposed to be visible in StoplightProject? @philsturgeon

File: packages/elements-core/src/components/Docs/HttpService/HttpService.tsx [hunk 2]
```diff
@@ -64,7 +63,9 @@ const HttpServiceComponent = React.memo<HttpServiceProps>(({ className, data, he
       ) : (
         <Box mb={10}>
           {description}
-          <PoweredByLink source={data.name ?? 'no-title'} pathname={pathname} packageType="elements" headless />
+          {pathname && (
+            <PoweredByLink source={data.name ?? 'no-title'} pathname={pathname} packageType="elements" headless />
+          )}
```
Comment (marcelltoth) [inline packages/elements-core/src/components/Docs/HttpService/HttpService.tsx:68]: I also find it weird that this depends on the pathname being present :\

File: packages/elements-core/src/components/Docs/HttpService/HttpService.tsx [hunk 3]
```diff
@@ -20,8 +19,8 @@ const enhanceVersionString = (version: string): string => {
 
 export type HttpServiceProps = DocsComponentProps<Partial<IHttpService>>;
 
-const HttpServiceComponent = React.memo<HttpServiceProps>(({ className, data, headless }) => {
-  const { search, pathname } = useLocation();
+const HttpServiceComponent = React.memo<HttpServiceProps>(({ className, data, headless, location = {} }) => {
+  const { search, pathname } = location;
```
Comment (marcelltoth) [inline packages/elements-core/src/components/Docs/HttpService/HttpService.tsx:23]: Can we maaybe pass in what we actually need, and not the entire `Location` object? Would be more versatile that way. But of course you can likely prove that this is what we need here.

File: packages/elements-core/src/components/Docs/HttpService/HttpService.tsx (hunk 2 above)
Comment (mpodlasin) [reply packages/elements-core/src/components/Docs/HttpService/HttpService.tsx:68]: If `pathname` is only a "nice to have" then I can make it optional in PoweredByLink. :shrug: 

But in practice it will work the same either way, so I chose simpler implementation.

File: packages/elements-core/src/components/Docs/HttpService/HttpService.tsx (hunk 3 above)
Comment (mpodlasin) [reply packages/elements-core/src/components/Docs/HttpService/HttpService.tsx:23]: I somewhat disagree.

If we decide that Docs components can have logic depending on location, I don't see a reason to not provide the whole location object in one go. 

If it turns out that other parameters are not necessary, no harm will be done.

If in the future more stuff will be necessary, it will be already there.

But I don't feel strongly about that either way :shrug:

**Comment by mpodlasin** [comment]
@philsturgeon @marcelltoth 

I would just add that in case we forget to pass location data, it will be easier to see that we screwed up if the component is missing altogether, rather that when it has a wrong url.

In fact even writing e2e test will be *a bit* easier.

File: packages/elements-core/src/components/Docs/HttpService/HttpService.tsx (hunk 1 above)
Comment (philsturgeon) [reply packages/elements-core/src/components/Docs/HttpService/HttpService.tsx]: Yeah we want powered by to show up on stoplightproject too.

To make it easier to read, there could be a hidePoweredBy variable or something like that, if its purely about platform internal. We might have an option to hide powered by if theyre on a certain plan too, so it would generally be a handy feature to have so long as its not a simple boolean in the control of the user.

**Comment by mpodlasin** [comment]
I am sorry, I wasn't thinking straight on friday afternoon.

This is PoweredByStoplight displayed in HttpService component in *stack layout*.

There techinically is already a prop to control if it should be displayed, and it is `headless` prop.

Check for `pathname` is just a typeguard and it will always be `true` in our usecases It's just me playing with TS nice.

And even if I add `showPoweredBy` or something, it will be still `showPoweredBy && pathname` in the condition itself, so it will not help to make things more readable in any ways. :shrug: 

I honestly don't know what I should do here.

**Review by marcelltoth — APPROVED** [review]

**Comment by philsturgeon** [comment]
@mpodlasin if it’s just type safe stuff not hidden functionality then it’s fine as is.

**Review by philsturgeon — APPROVED** [review]
